In [423]:
import pandas as pd
data = pd.read_csv('88-92.csv',usecols=[ 'GDP/面积', '路距','熵','湖距','label'])
print(data.shape) # (235, 5)
print(type(data)) 

(235, 5)
<class 'pandas.core.frame.DataFrame'>


In [424]:
data.head()

GDP/面积        路距         熵        湖距  label
0  0.990951  0.618756  0.657462  0.665135      0
1  0.973786  0.811400  0.657462  0.737388      0
2  0.963077  0.737421  0.657462  0.773321      0
3  0.980047  0.775631  0.657462  0.768556      0
4  0.989406  0.719091  0.657462  0.778399      0

In [425]:
# 划分数据获取X，y
X = data[['GDP/面积', '路距','熵','湖距']]
Y = data['label']
print(X.shape)
print(Y.shape)
print(type(Y))
print(Y.head())

(235, 4)
(235,)
<class 'pandas.core.series.Series'>
0    0
1    0
2    0
3    0
4    0
Name: label, dtype: int64


In [426]:
# 修改X,y数据类型：<class 'pandas.core.frame.DataFrame'> ---> <class 'numpy.ndarray'>
import numpy as np
X = np.array(X)
Y = Y.values.tolist()
print(type(Y))
print(X.shape)


# X= tf.convert_to_tensor(X,dtype=tf.float32)
# y = tf.convert_to_tensor(y,dtype=tf.float32)
# X = X.astype(float)
# y = y.astype(float)
print(type(X))


<class 'list'>
(235, 4)
<class 'numpy.ndarray'>


In [427]:
print("type_x:",type(X))
print("type_y:",type(Y))
print(x.shape) #(?, 4)
# print(y.shape)#(?, 1)

type_x: <class 'numpy.ndarray'>
type_y: <class 'list'>
(?, 4)


神经网络实现二分类

In [428]:
import tensorflow as tf

w1 = tf.Variable(tf.random_normal([4,3],stddev=1,seed=1))  # 因为含有4个属性值
w2 = tf.Variable(tf.random_normal([3,1],stddev=1,seed=1))

# w1 = tf.convert_to_tensor(w1)
# w1 = tf.convert_to_tensor(w1)

In [429]:
#定义placeholder作为存放输入数据的地方，这里维度不一定要定义
x = tf.placeholder(tf.float32,shape=(None,4),name = 'x-input')  # 2个属性特征值
y_ = tf.placeholder(tf.float32,shape=(None,1),name = 'y-input')#用做标签
 
#定义神经网络前向传播的过程，就是矩阵相乘  两层神经网络
a = tf.matmul(x,w1)
y = tf.matmul(a,w2)
 
#定义损失函数和反向传播算法
#用sigmoid将函数收敛到0~1之间
y = tf.sigmoid(y)

In [430]:
#定义交叉熵损失函数，用于权衡输出值和标签值的差异
cross_entropy = -tf.reduce_mean(
    y_*tf.log(tf.clip_by_value(y,1e-10,1.0))
    +(1-y)*tf.log(tf.clip_by_value(1-y,1e-10,1.0))
)

In [431]:
#优化算法lr=0.001
train_step = tf.train.AdamOptimizer(0.001).minimize(cross_entropy)

In [432]:
"""
# 张量转化为ndarray  t为张量
array = session.run(t)
"""
"""
testy = X[0:5]
print(type(testy))
sess = tf.Session()
ny = testy.eval(session=sess)
print(type(ny))
"""
print(Y)
print("len_Y",len(Y))
list = Y
Y = []
for i in list:
    Y.append([i])
print("-----------------------------")
print(Y)
print("len_Y",len(Y))

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
len_Y 235
-----------------------------
[[0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1]

In [433]:
dataset_size = 235
batch_size = 5
# tf.reset_default_graph()

#创建一个会话来运行TensorFlow程序
with tf.Session() as sess:
    init_op = tf.global_variables_initializer()#全体初始化
    sess.run(init_op)#先跑一下初始化是必须的
 
    print(sess.run(w1))#输出看看当前的参数
    print(sess.run(w2))

#设定训练的轮数
    STEPS = 5000
    for i in range(STEPS):
        start = (i*batch_size)%dataset_size#每次选取batch_size个样本进行训练
        end = min(start+batch_size,dataset_size)
#         print("nx before:",type(X[start:end]))
#         nx = X[start:end].eval(session=sess)
#         print("nx after",type(nx))  # 转换成功
#         print("ny before",type(ny))
#         ny = y[start:end].eval(session=sess)
#         nx = y[start:end]
#         print(type(nx))
#         ny = y[start:end].eval(session=sess)
        
#     通过选取的样本训练神经网络并更新参数
        sess.run(train_step,feed_dict={x:X[start:end],y_:Y[start:end]})
        if i%1000 == 0:
            total_cross_entropy = sess.run(cross_entropy,feed_dict={x:X,y_:Y})
            print("cross entropy on all data is",total_cross_entropy)
    print(sess.run(w1))
    print(sess.run(w2))

[[-0.8113182   1.4845988   0.06532937]
 [-2.4427042   0.0992484   0.5912243 ]
 [ 0.59282297 -2.1229296  -0.72289723]
 [-0.05627038  0.6435448  -0.26432407]]
[[-0.8113182 ]
 [ 1.4845988 ]
 [ 0.06532937]]
cross entropy on all data is 0.32340625
cross entropy on all data is 0.0064331894
cross entropy on all data is 0.0015025854
cross entropy on all data is 0.0005992206
cross entropy on all data is 0.00029015588
[[-1.2989208e+00  1.9476891e+00 -1.1711992e+00]
 [-2.9702058e+00  5.9634757e-01 -7.3553973e-01]
 [-1.2355413e-03 -1.5619457e+00 -2.1035061e+00]
 [-6.3040429e-01  1.1855305e+00 -1.6215870e+00]]
[[-1.3626207]
 [ 2.0756211]
 [-1.1959031]]


* https://blog.csdn.net/hejunqing14/article/details/52688825
* https://stackoverflow.com/questions/38306330/typeerror-fetch-argument-has-invalid-type-float32-must-be-a-string-or-tensor
* https://blog.csdn.net/qq_33431368/article/details/84454635
* https://www.cnblogs.com/smartwhite/p/8946606.html